name: manycooks
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.1
  community_material_icon: ^5.9.55
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  dots_indicator: ^2.0.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_downloader: ^1.6.1
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.0.7
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  keyboard_visibility: ^0.5.6
  provider: ^6.0.0
  rounded_loading_button: ^2.0.5
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  zefyrka: ^1.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Georgia Belle
      fonts:
        - asset: fonts/Georgia Belle Hollow.ttf
          weight: 700
        - asset: fonts/Georgia Belle Skinny.ttf
          weight: 300
        - asset: fonts/Georgia Belle.ttf
    - family: GreatVibes
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
    - family: HEY LEMON
      fonts:
        - asset: fonts/HEY LEMON.otf
    - family: KramforsDemoRegular
      fonts:
        - asset: fonts/KramforsDemoRegular.ttf
    - family: My Celery
      fonts:
        - asset: fonts/My Celery.ttf
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-BlackItalic.ttf
          style: italic
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 900
        - asset: fonts/Nunito-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 400
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-LightItalic.ttf
          style: italic
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
    - family: Ocean Summer
      fonts:
        - asset: fonts/Ocean Summer.otf
        - asset: fonts/Ocean Summer.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 900
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 800
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 200
          style: italic
    - family: RemachineScript_Personal_Use
      fonts:
        - asset: fonts/RemachineScript_Personal_Use.ttf
    - family: TAKE CUTE
      fonts:
        - asset: fonts/TAKE CUTE.otf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
